package bugallolugomizrahi.interfaz;

import bugallolugomizrahi.MazeGenerator;
import static bugallolugomizrahi.MazeGenerator.HEIGHT;
import static bugallolugomizrahi.MazeGenerator.TILE_WIDTH;
import static bugallolugomizrahi.MazeGenerator.WIDTH;
import bugallolugomizrahi.Randomizer;
import java.awt.Dimension;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class Ventana2 extends javax.swing.JFrame {
// Aqui va la informacion que se comparte entre ventanas, declaradas como variables globales public static

    public static Ventana1 v1;
    public static JFrame frame = new JFrame();
//    public static MazeGenerator maze = new MazeGenerator();

    public Ventana2(Ventana1 v1) {
        initComponents();
        this.v1 = v1;
        v1.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        salir = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        generarMapa = new javax.swing.JButton();
        verde = new javax.swing.JLabel();
        rojo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(242, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 70, -1));

        anterior.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        anterior.setText("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });
        jPanel1.add(anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 70, -1));

        generarMapa.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        generarMapa.setText("Bosquejo del mapa");
        generarMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarMapaActionPerformed(evt);
            }
        });
        jPanel1.add(generarMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 200, 40));

        verde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugallolugomizrahi/imagenes/verde.png"))); // NOI18N
        jPanel1.add(verde, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        rojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugallolugomizrahi/imagenes/rojo.png"))); // NOI18N
        jPanel1.add(rojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel1.setText("El cuadrado rojo indica la salida");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel2.setText("El cuadrado verde indica la entrada");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void generarMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarMapaActionPerformed

        int x = 0;
        int y = 0;

        try {
            x = Integer.parseInt(v1.x);
            y = Integer.parseInt(v1.y);
            if (x < 4 || x >= 150 || y < 4 || y >= 150) {
                throw new Exception("Error, las dimensiones no pueden ser menores a dos");
            }

            MazeGenerator.HEIGHT = y;
            MazeGenerator.WIDTH = x;
            MazeGenerator mazeGen = new MazeGenerator();
            if (x > y) {
                if (x < 15) {
                    MazeGenerator.TILE_HEIGHT = 25;
                    MazeGenerator.TILE_WIDTH = 25;
                } else if (x < 30) {
                    MazeGenerator.TILE_HEIGHT = 20;
                    MazeGenerator.TILE_WIDTH = 20;
                } else if (x < 50) {
                    MazeGenerator.TILE_HEIGHT = 15;
                    MazeGenerator.TILE_WIDTH = 15;
                } else {
                    MazeGenerator.TILE_HEIGHT = 5;
                    MazeGenerator.TILE_WIDTH = 5;
                }
            } else {
                if (y < 15) {
                    MazeGenerator.TILE_HEIGHT = 25;
                    MazeGenerator.TILE_WIDTH = 25;
                } else if (y < 30) {
                    MazeGenerator.TILE_HEIGHT = 20;
                    MazeGenerator.TILE_WIDTH = 20;
                } else if (y < 50) {
                    MazeGenerator.TILE_HEIGHT = 15;
                    MazeGenerator.TILE_WIDTH = 15;
                } else {
                    MazeGenerator.TILE_HEIGHT = 5;
                    MazeGenerator.TILE_WIDTH = 5;
                }
            }

            mazeGen.generate();
            mazeGen.setSize(x, y);
            frame.setSize(1280, 720);
            frame.add(mazeGen);
            frame.setResizable(false);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
            frame.setDefaultCloseOperation(EXIT_ON_CLOSE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al momento de ingresar datos, por favor ingrese numeros entre 4 y 150");
            this.dispose();
            v1.setVisible(true);
        }


    }//GEN-LAST:event_generarMapaActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        this.dispose();
        v1.setVisible(true);
    }//GEN-LAST:event_anteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JButton generarMapa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel rojo;
    private javax.swing.JButton salir;
    private javax.swing.JLabel verde;
    // End of variables declaration//GEN-END:variables
}
